[2025-05-02T06:15:46.415+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-02T06:15:46.430+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dags_bash_select_fruit.t2_avocado manual__2025-05-02T06:15:44.660472+00:00 [queued]>
[2025-05-02T06:15:46.438+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dags_bash_select_fruit.t2_avocado manual__2025-05-02T06:15:44.660472+00:00 [queued]>
[2025-05-02T06:15:46.438+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-05-02T06:15:46.450+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): t2_avocado> on 2025-05-02 06:15:44.660472+00:00
[2025-05-02T06:15:46.459+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3569) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-02T06:15:46.460+0000] {standard_task_runner.py:72} INFO - Started process 3578 to run task
[2025-05-02T06:15:46.461+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dags_bash_select_fruit', 't2_avocado', 'manual__2025-05-02T06:15:44.660472+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/dags_bash_select_fruit.py', '--cfg-path', '/tmp/tmptdbhd7i7']
[2025-05-02T06:15:46.462+0000] {standard_task_runner.py:105} INFO - Job 8: Subtask t2_avocado
[2025-05-02T06:15:46.704+0000] {task_command.py:467} INFO - Running <TaskInstance: dags_bash_select_fruit.t2_avocado manual__2025-05-02T06:15:44.660472+00:00 [running]> on host ec0a166f965f
[2025-05-02T06:15:46.761+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dags_bash_select_fruit' AIRFLOW_CTX_TASK_ID='t2_avocado' AIRFLOW_CTX_EXECUTION_DATE='2025-05-02T06:15:44.660472+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-02T06:15:44.660472+00:00'
[2025-05-02T06:15:46.761+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-05-02T06:15:46.761+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-05-02T06:15:46.761+0000] {logging_mixin.py:190} INFO - Current task name:t2_avocado state:running start_date:2025-05-02 06:15:46.430665+00:00
[2025-05-02T06:15:46.762+0000] {logging_mixin.py:190} INFO - Dag name:dags_bash_select_fruit and current dag run status:running
[2025-05-02T06:15:46.762+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-02T06:15:46.762+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-05-02T06:15:46.763+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', '/opt/***/plugins/shell/select_fruit.sh AVOCADO']
[2025-05-02T06:15:46.775+0000] {subprocess.py:99} INFO - Output:
[2025-05-02T06:15:46.776+0000] {subprocess.py:106} INFO - /usr/bin/bash: line 1: /opt/***/plugins/shell/select_fruit.sh: Permission denied
[2025-05-02T06:15:46.777+0000] {subprocess.py:110} INFO - Command exited with return code 126
[2025-05-02T06:15:46.786+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 126.
[2025-05-02T06:15:46.790+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-05-02T06:15:46.790+0000] {logging_mixin.py:190} INFO - Task start:2025-05-02 06:15:46.430665+00:00 end:2025-05-02 06:15:46.790230+00:00 duration:0.359565
[2025-05-02T06:15:46.791+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): t2_avocado> dag:<DAG: dags_bash_select_fruit> dagrun:<DagRun dags_bash_select_fruit @ 2025-05-02 06:15:44.660472+00:00: manual__2025-05-02T06:15:44.660472+00:00, state:running, queued_at: 2025-05-02 06:15:44.668962+00:00. externally triggered: True>
[2025-05-02T06:15:46.791+0000] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 126.
[2025-05-02T06:15:46.791+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=dags_bash_select_fruit, task_id=t2_avocado, run_id=manual__2025-05-02T06:15:44.660472+00:00, execution_date=20250502T061544, start_date=20250502T061546, end_date=20250502T061546
[2025-05-02T06:15:46.812+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-02T06:15:46.812+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 8 for task t2_avocado (Bash command failed. The command returned a non-zero exit code 126.; 3578)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 126.
[2025-05-02T06:15:46.835+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-02T06:15:46.990+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-02T06:15:46.991+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
