[2025-05-07T04:30:17.437+0000] {processor.py:186} INFO - Started process (PID=48605) to work on /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:30:17.437+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags_bash_with_macro_eg1.py for tasks to queue
[2025-05-07T04:30:17.438+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:30:17.438+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:30:17.445+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:30:17.442+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_macro_eg1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_macro_eg1.py", line 12, in <module>
    bash_task_2 = BashOperator(
                  ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 166, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 959, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: bash_task_2). Invalid arguments were:
**kwargs: {'end': {'START_DATE': '{{}}', 'END_DATE': '{{}}'}}
[2025-05-07T04:30:17.445+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:30:17.458+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags_bash_with_macro_eg1.py took 0.026 seconds
[2025-05-07T04:30:48.016+0000] {processor.py:186} INFO - Started process (PID=48678) to work on /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:30:48.026+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags_bash_with_macro_eg1.py for tasks to queue
[2025-05-07T04:30:48.027+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:30:48.027+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:30:48.033+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:30:48.032+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_macro_eg1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_macro_eg1.py", line 12, in <module>
    bash_task_2 = BashOperator(
                  ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 166, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 959, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: bash_task_2). Invalid arguments were:
**kwargs: {'end': {'START_DATE': '{{}}', 'END_DATE': '{{}}'}}
[2025-05-07T04:30:48.034+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:30:48.049+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags_bash_with_macro_eg1.py took 0.037 seconds
[2025-05-07T04:31:18.571+0000] {processor.py:186} INFO - Started process (PID=48754) to work on /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:31:18.580+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags_bash_with_macro_eg1.py for tasks to queue
[2025-05-07T04:31:18.581+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:31:18.581+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:31:18.586+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:31:18.585+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_macro_eg1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_macro_eg1.py", line 12, in <module>
    bash_task_2 = BashOperator(
                  ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 166, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 959, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: bash_task_2). Invalid arguments were:
**kwargs: {'end': {'START_DATE': '{{}}', 'END_DATE': '{{}}'}}
[2025-05-07T04:31:18.586+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:31:18.603+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags_bash_with_macro_eg1.py took 0.036 seconds
[2025-05-07T04:31:44.669+0000] {processor.py:186} INFO - Started process (PID=48821) to work on /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:31:44.677+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags_bash_with_macro_eg1.py for tasks to queue
[2025-05-07T04:31:44.678+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:31:44.678+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:31:44.683+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:31:44.682+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_macro_eg1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_macro_eg1.py", line 12, in <module>
    bash_task_2 = BashOperator(
                  ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 166, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 959, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: bash_task_2). Invalid arguments were:
**kwargs: {'end': {'START_DATE': '{{ data_interval_start }}', 'END_DATE': '{{ data_interval_end+}}'}}
[2025-05-07T04:31:44.683+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:31:44.700+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags_bash_with_macro_eg1.py took 0.036 seconds
[2025-05-07T04:32:13.406+0000] {processor.py:186} INFO - Started process (PID=48897) to work on /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:32:13.408+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags_bash_with_macro_eg1.py for tasks to queue
[2025-05-07T04:32:13.411+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:32:13.410+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:32:13.417+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:32:13.415+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_macro_eg1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_macro_eg1.py", line 14, in <module>
    bash_task_2 = BashOperator(
                  ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 166, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 959, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: bash_task_2). Invalid arguments were:
**kwargs: {'end': {'START_DATE': '{{ data_interval_start }}', 'END_DATE': '{{ data_interval_end+relativedelta.relativedelta(days=-1)}}'}}
[2025-05-07T04:32:13.418+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:32:13.443+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags_bash_with_macro_eg1.py took 0.046 seconds
[2025-05-07T04:32:43.487+0000] {processor.py:186} INFO - Started process (PID=48973) to work on /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:32:43.488+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags_bash_with_macro_eg1.py for tasks to queue
[2025-05-07T04:32:43.489+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:32:43.489+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:32:43.495+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:32:43.494+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_macro_eg1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_macro_eg1.py", line 14, in <module>
    bash_task_2 = BashOperator(
                  ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 166, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 959, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: bash_task_2). Invalid arguments were:
**kwargs: {'end': {'START_DATE': '{{ data_interval_start }}', 'END_DATE': '{{ data_interval_end+relativedelta.relativedelta(days=-1)}}'}}
[2025-05-07T04:32:43.496+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:32:43.513+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags_bash_with_macro_eg1.py took 0.033 seconds
[2025-05-07T04:32:49.769+0000] {processor.py:186} INFO - Started process (PID=48980) to work on /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:32:49.769+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags_bash_with_macro_eg1.py for tasks to queue
[2025-05-07T04:32:49.770+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:32:49.770+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:32:49.776+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:32:49.775+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_macro_eg1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_macro_eg1.py", line 14, in <module>
    bash_task_2 = BashOperator(
                  ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 166, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 959, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: bash_task_2). Invalid arguments were:
**kwargs: {'end': {'START_DATE': '{{ data_interval_start.in_timezone("Asia/Seoul") }}', 'END_DATE': '{{ data_interval_end+relativedelta.relativedelta(days=-1)}}'}}
[2025-05-07T04:32:49.777+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:32:49.794+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags_bash_with_macro_eg1.py took 0.031 seconds
[2025-05-07T04:33:19.961+0000] {processor.py:186} INFO - Started process (PID=49056) to work on /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:33:19.970+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags_bash_with_macro_eg1.py for tasks to queue
[2025-05-07T04:33:19.971+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:33:19.971+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:33:19.976+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:33:19.975+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_macro_eg1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_macro_eg1.py", line 14, in <module>
    bash_task_2 = BashOperator(
                  ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 166, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 959, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: bash_task_2). Invalid arguments were:
**kwargs: {'end': {'START_DATE': '{{ data_interval_start.in_timezone("Asia/Seoul") }}', 'END_DATE': '{{ data_interval_end+relativedelta.relativedelta(days=-1)}}'}}
[2025-05-07T04:33:19.977+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:33:19.994+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags_bash_with_macro_eg1.py took 0.037 seconds
[2025-05-07T04:33:37.708+0000] {processor.py:186} INFO - Started process (PID=49126) to work on /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:33:37.710+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags_bash_with_macro_eg1.py for tasks to queue
[2025-05-07T04:33:37.711+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:33:37.710+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:33:37.718+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:33:37.716+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_macro_eg1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_macro_eg1.py", line 14, in <module>
    bash_task_2 = BashOperator(
                  ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 166, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 959, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: bash_task_2). Invalid arguments were:
**kwargs: {'end': {'START_DATE': '{{ data_interval_start.in_timezone("Asia/Seoul") }}', 'END_DATE': '{{ data_interval_end.in_timezone("Asia/Seoul")+relativedelta.relativedelta(days=-1)}}'}}
[2025-05-07T04:33:37.719+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:33:37.736+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags_bash_with_macro_eg1.py took 0.033 seconds
[2025-05-07T04:34:08.619+0000] {processor.py:186} INFO - Started process (PID=49202) to work on /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:34:08.620+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags_bash_with_macro_eg1.py for tasks to queue
[2025-05-07T04:34:08.621+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:34:08.621+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:34:08.626+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:34:08.625+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_macro_eg1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_macro_eg1.py", line 14, in <module>
    bash_task_2 = BashOperator(
                  ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 166, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 959, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: bash_task_2). Invalid arguments were:
**kwargs: {'end': {'START_DATE': '{{ data_interval_start.in_timezone("Asia/Seoul") }}', 'END_DATE': '{{ data_interval_end.in_timezone("Asia/Seoul")+relativedelta.relativedelta(days=-1)}}'}}
[2025-05-07T04:34:08.627+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:34:08.641+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags_bash_with_macro_eg1.py took 0.026 seconds
[2025-05-07T04:34:38.963+0000] {processor.py:186} INFO - Started process (PID=49278) to work on /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:34:38.964+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags_bash_with_macro_eg1.py for tasks to queue
[2025-05-07T04:34:38.965+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:34:38.965+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:34:38.971+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:34:38.969+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_macro_eg1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_macro_eg1.py", line 14, in <module>
    bash_task_2 = BashOperator(
                  ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 166, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 959, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: bash_task_2). Invalid arguments were:
**kwargs: {'end': {'START_DATE': '{{ data_interval_start.in_timezone("Asia/Seoul") }}', 'END_DATE': '{{ data_interval_end.in_timezone("Asia/Seoul")+relativedelta.relativedelta(days=-1)}}'}}
[2025-05-07T04:34:38.971+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:34:38.985+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags_bash_with_macro_eg1.py took 0.028 seconds
[2025-05-07T04:35:04.273+0000] {processor.py:186} INFO - Started process (PID=49354) to work on /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:35:04.274+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags_bash_with_macro_eg1.py for tasks to queue
[2025-05-07T04:35:04.275+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:35:04.275+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:35:04.282+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:35:04.280+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_macro_eg1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_macro_eg1.py", line 14, in <module>
    bash_task_2 = BashOperator(
                  ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 166, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 959, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: bash_task_2). Invalid arguments were:
**kwargs: {'end': {'START_DATE': '{{ data_interval_start.in_timezone("Asia/Seoul") }}', 'END_DATE': '{{ data_interval_end.in_timezone("Asia/Seoul")+macros.dateutil.relativedelta.relativedelta(days=-1)}}'}}
[2025-05-07T04:35:04.283+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:35:04.302+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags_bash_with_macro_eg1.py took 0.035 seconds
[2025-05-07T04:35:34.455+0000] {processor.py:186} INFO - Started process (PID=49430) to work on /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:35:34.458+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags_bash_with_macro_eg1.py for tasks to queue
[2025-05-07T04:35:34.459+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:35:34.459+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:35:34.466+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:35:34.464+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_macro_eg1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_macro_eg1.py", line 14, in <module>
    bash_task_2 = BashOperator(
                  ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 166, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 959, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: bash_task_2). Invalid arguments were:
**kwargs: {'end': {'START_DATE': '{{ data_interval_start.in_timezone("Asia/Seoul") }}', 'END_DATE': '{{ data_interval_end.in_timezone("Asia/Seoul")+macros.dateutil.relativedelta.relativedelta(days=-1)}}'}}
[2025-05-07T04:35:34.467+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:35:34.495+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags_bash_with_macro_eg1.py took 0.050 seconds
[2025-05-07T04:35:44.533+0000] {processor.py:186} INFO - Started process (PID=49431) to work on /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:35:44.535+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags_bash_with_macro_eg1.py for tasks to queue
[2025-05-07T04:35:44.536+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:35:44.536+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:35:44.541+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:35:44.539+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_macro_eg1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_macro_eg1.py", line 14, in <module>
    bash_task_2 = BashOperator(
                  ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 166, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 959, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: bash_task_2). Invalid arguments were:
**kwargs: {'end': {'START_DATE': '{{ data_interval_start.in_timezone("Asia/Seoul") | ds }}', 'END_DATE': '{{ (data_interval_end.in_timezone("Asia/Seoul")+macros.dateutil.relativedelta.relativedelta(days=-1)) | ds}}'}}
[2025-05-07T04:35:44.541+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:35:44.557+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags_bash_with_macro_eg1.py took 0.029 seconds
[2025-05-07T04:36:14.981+0000] {processor.py:186} INFO - Started process (PID=49507) to work on /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:36:14.982+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags_bash_with_macro_eg1.py for tasks to queue
[2025-05-07T04:36:14.983+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:36:14.983+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:36:14.988+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:36:14.987+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_macro_eg1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_macro_eg1.py", line 14, in <module>
    bash_task_2 = BashOperator(
                  ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 166, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 959, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: bash_task_2). Invalid arguments were:
**kwargs: {'end': {'START_DATE': '{{ data_interval_start.in_timezone("Asia/Seoul") | ds }}', 'END_DATE': '{{ (data_interval_end.in_timezone("Asia/Seoul")+macros.dateutil.relativedelta.relativedelta(days=-1)) | ds}}'}}
[2025-05-07T04:36:14.989+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:36:15.004+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags_bash_with_macro_eg1.py took 0.029 seconds
[2025-05-07T04:36:45.504+0000] {processor.py:186} INFO - Started process (PID=49583) to work on /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:36:45.505+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags_bash_with_macro_eg1.py for tasks to queue
[2025-05-07T04:36:45.506+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:36:45.506+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:36:45.512+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:36:45.510+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_macro_eg1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_macro_eg1.py", line 14, in <module>
    bash_task_2 = BashOperator(
                  ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 166, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 959, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: bash_task_2). Invalid arguments were:
**kwargs: {'end': {'START_DATE': '{{ data_interval_start.in_timezone("Asia/Seoul") | ds }}', 'END_DATE': '{{ (data_interval_end.in_timezone("Asia/Seoul")+macros.dateutil.relativedelta.relativedelta(days=-1)) | ds}}'}}
[2025-05-07T04:36:45.513+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:36:45.527+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags_bash_with_macro_eg1.py took 0.027 seconds
[2025-05-07T04:37:02.957+0000] {processor.py:186} INFO - Started process (PID=49635) to work on /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:37:02.958+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags_bash_with_macro_eg1.py for tasks to queue
[2025-05-07T04:37:02.960+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:37:02.959+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:37:02.966+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:37:02.964+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_macro_eg1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_macro_eg1.py", line 14, in <module>
    bash_task_2 = BashOperator(
                  ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 166, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 959, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: bash_task_2). Invalid arguments were:
**kwargs: {'end': {'START_DATE': '{{ data_interval_start.in_timezone("Asia/Seoul") | ds }}', 'END_DATE': '{{ (data_interval_end.in_timezone("Asia/Seoul")+macros.dateutil.relativedelta.relativedelta(days=-1)) | ds}}'}}
[2025-05-07T04:37:02.966+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:37:02.986+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags_bash_with_macro_eg1.py took 0.034 seconds
[2025-05-07T04:37:06.212+0000] {processor.py:186} INFO - Started process (PID=49645) to work on /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:37:06.213+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags_bash_with_macro_eg1.py for tasks to queue
[2025-05-07T04:37:06.214+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:37:06.213+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:37:06.222+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:37:06.220+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_macro_eg1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_macro_eg1.py", line 14, in <module>
    bash_task_1 = BashOperator(
                  ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 166, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 959, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: bash_task_1). Invalid arguments were:
**kwargs: {'end': {'START_DATE': '{{ data_interval_start.in_timezone("Asia/Seoul") | ds }}', 'END_DATE': '{{ (data_interval_end.in_timezone("Asia/Seoul")+macros.dateutil.relativedelta.relativedelta(days=-1)) | ds}}'}}
[2025-05-07T04:37:06.222+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:37:06.243+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags_bash_with_macro_eg1.py took 0.036 seconds
[2025-05-07T04:37:36.466+0000] {processor.py:186} INFO - Started process (PID=49721) to work on /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:37:36.467+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags_bash_with_macro_eg1.py for tasks to queue
[2025-05-07T04:37:36.468+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:37:36.468+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:37:36.473+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:37:36.471+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_macro_eg1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_macro_eg1.py", line 14, in <module>
    bash_task_1 = BashOperator(
                  ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 166, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 959, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: bash_task_1). Invalid arguments were:
**kwargs: {'end': {'START_DATE': '{{ data_interval_start.in_timezone("Asia/Seoul") | ds }}', 'END_DATE': '{{ (data_interval_end.in_timezone("Asia/Seoul")+macros.dateutil.relativedelta.relativedelta(days=-1)) | ds}}'}}
[2025-05-07T04:37:36.473+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:37:36.489+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags_bash_with_macro_eg1.py took 0.028 seconds
[2025-05-07T04:38:06.706+0000] {processor.py:186} INFO - Started process (PID=49797) to work on /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:38:06.708+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags_bash_with_macro_eg1.py for tasks to queue
[2025-05-07T04:38:06.709+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:38:06.709+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:38:06.715+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:38:06.713+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_macro_eg1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_macro_eg1.py", line 14, in <module>
    bash_task_1 = BashOperator(
                  ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 166, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 959, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: bash_task_1). Invalid arguments were:
**kwargs: {'end': {'START_DATE': '{{ data_interval_start.in_timezone("Asia/Seoul") | ds }}', 'END_DATE': '{{ (data_interval_end.in_timezone("Asia/Seoul")+macros.dateutil.relativedelta.relativedelta(days=-1)) | ds}}'}}
[2025-05-07T04:38:06.716+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:38:06.737+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags_bash_with_macro_eg1.py took 0.036 seconds
[2025-05-07T04:38:30.668+0000] {processor.py:186} INFO - Started process (PID=49846) to work on /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:38:30.670+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags_bash_with_macro_eg1.py for tasks to queue
[2025-05-07T04:38:30.671+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:38:30.671+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:38:30.676+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:38:30.675+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_macro_eg1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_macro_eg1.py", line 14, in <module>
    bash_task_1 = BashOperator(
                  ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 166, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 959, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: bash_task_1). Invalid arguments were:
**kwargs: {'end': {'START_DATE': '{{ data_interval_start.in_timezone("Asia/Seoul") | ds }}', 'END_DATE': '{{ (data_interval_end.in_timezone("Asia/Seoul")+macros.dateutil.relativedelta.relativedelta(days=-1)) | ds}}'}}
[2025-05-07T04:38:30.677+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:38:30.695+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags_bash_with_macro_eg1.py took 0.031 seconds
[2025-05-07T04:39:01.474+0000] {processor.py:186} INFO - Started process (PID=49922) to work on /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:39:01.475+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags_bash_with_macro_eg1.py for tasks to queue
[2025-05-07T04:39:01.476+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:39:01.476+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:39:01.481+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:39:01.479+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_macro_eg1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_macro_eg1.py", line 14, in <module>
    bash_task_1 = BashOperator(
                  ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 166, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 959, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: bash_task_1). Invalid arguments were:
**kwargs: {'end': {'START_DATE': '{{ data_interval_start.in_timezone("Asia/Seoul") | ds }}', 'END_DATE': '{{ (data_interval_end.in_timezone("Asia/Seoul")+macros.dateutil.relativedelta.relativedelta(days=-1)) | ds}}'}}
[2025-05-07T04:39:01.481+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:39:01.496+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags_bash_with_macro_eg1.py took 0.027 seconds
[2025-05-07T04:39:31.756+0000] {processor.py:186} INFO - Started process (PID=49998) to work on /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:39:31.764+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags_bash_with_macro_eg1.py for tasks to queue
[2025-05-07T04:39:31.764+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:39:31.764+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:39:31.770+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:39:31.768+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_macro_eg1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_macro_eg1.py", line 14, in <module>
    bash_task_1 = BashOperator(
                  ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 166, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 959, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: bash_task_1). Invalid arguments were:
**kwargs: {'end': {'START_DATE': '{{ data_interval_start.in_timezone("Asia/Seoul") | ds }}', 'END_DATE': '{{ (data_interval_end.in_timezone("Asia/Seoul")+macros.dateutil.relativedelta.relativedelta(days=-1)) | ds}}'}}
[2025-05-07T04:39:31.770+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:39:31.787+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags_bash_with_macro_eg1.py took 0.036 seconds
[2025-05-07T04:40:02.301+0000] {processor.py:186} INFO - Started process (PID=50074) to work on /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:40:02.303+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags_bash_with_macro_eg1.py for tasks to queue
[2025-05-07T04:40:02.304+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:40:02.304+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:40:02.309+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:40:02.308+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_macro_eg1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_macro_eg1.py", line 14, in <module>
    bash_task_1 = BashOperator(
                  ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 166, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 959, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: bash_task_1). Invalid arguments were:
**kwargs: {'end': {'START_DATE': '{{ data_interval_start.in_timezone("Asia/Seoul") | ds }}', 'END_DATE': '{{ (data_interval_end.in_timezone("Asia/Seoul")+macros.dateutil.relativedelta.relativedelta(days=-1)) | ds}}'}}
[2025-05-07T04:40:02.309+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:40:02.326+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags_bash_with_macro_eg1.py took 0.029 seconds
[2025-05-07T04:40:32.802+0000] {processor.py:186} INFO - Started process (PID=50151) to work on /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:40:32.804+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags_bash_with_macro_eg1.py for tasks to queue
[2025-05-07T04:40:32.805+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:40:32.805+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:40:32.810+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:40:32.808+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_macro_eg1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_macro_eg1.py", line 14, in <module>
    bash_task_1 = BashOperator(
                  ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 166, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 959, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: bash_task_1). Invalid arguments were:
**kwargs: {'end': {'START_DATE': '{{ data_interval_start.in_timezone("Asia/Seoul") | ds }}', 'END_DATE': '{{ (data_interval_end.in_timezone("Asia/Seoul")+macros.dateutil.relativedelta.relativedelta(days=-1)) | ds}}'}}
[2025-05-07T04:40:32.811+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_macro_eg1.py
[2025-05-07T04:40:32.827+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags_bash_with_macro_eg1.py took 0.031 seconds
