[2025-05-12T08:34:20.984+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-12T08:34:21.034+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dags_bash_python_with_xcom.bash_pull scheduled__2025-05-11T00:30:00+00:00 [queued]>
[2025-05-12T08:34:21.056+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dags_bash_python_with_xcom.bash_pull scheduled__2025-05-11T00:30:00+00:00 [queued]>
[2025-05-12T08:34:21.057+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-05-12T08:34:21.339+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): bash_pull> on 2025-05-11 00:30:00+00:00
[2025-05-12T08:34:21.354+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=196) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-12T08:34:21.357+0000] {standard_task_runner.py:72} INFO - Started process 206 to run task
[2025-05-12T08:34:21.358+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dags_bash_python_with_xcom', 'bash_pull', 'scheduled__2025-05-11T00:30:00+00:00', '--job-id', '155', '--raw', '--subdir', 'DAGS_FOLDER/dags_bash_python_with_xcom.py', '--cfg-path', '/tmp/tmpft0c3m85']
[2025-05-12T08:34:21.360+0000] {standard_task_runner.py:105} INFO - Job 155: Subtask bash_pull
[2025-05-12T08:34:21.477+0000] {task_command.py:467} INFO - Running <TaskInstance: dags_bash_python_with_xcom.bash_pull scheduled__2025-05-11T00:30:00+00:00 [running]> on host 11348a8299f1
[2025-05-12T08:34:21.606+0000] {abstractoperator.py:783} ERROR - Exception rendering Jinja template for task 'bash_pull', field 'env'. Template: {'STATUS': '{{ ti.xcom_pull(task_ids=:"python_push")["status"]}}', 'DATA': '{{ti.xcom_pull(task_ids="python_push")["data"]}}', 'OPTIONS_CNT': '{{ti.xcom_pull(task_ids="python_push")["options_cnt]}}'}
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/abstractoperator.py", line 775, in _do_render_template_fields
    rendered_content = self.render_template(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 185, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 170, in render_template
    template = jinja_env.from_string(value)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/environment.py", line 1111, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
                               ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/environment.py", line 771, in compile
    self.handle_exception(source=source_hint)
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected ':'
[2025-05-12T08:34:21.614+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3117, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context, jinja_env=jinja_env)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3540, in render_templates
    original_task.render_template_fields(context, jinja_env)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 1442, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/abstractoperator.py", line 775, in _do_render_template_fields
    rendered_content = self.render_template(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 185, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 170, in render_template
    template = jinja_env.from_string(value)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/environment.py", line 1111, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
                               ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/environment.py", line 771, in compile
    self.handle_exception(source=source_hint)
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected ':'
[2025-05-12T08:34:21.636+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-05-12T08:34:21.636+0000] {logging_mixin.py:190} INFO - Task start:2025-05-12 08:34:21.035709+00:00 end:2025-05-12 08:34:21.634884+00:00 duration:0.599175
[2025-05-12T08:34:21.637+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): bash_pull> dag:<DAG: dags_bash_python_with_xcom> dagrun:<DagRun dags_bash_python_with_xcom @ 2025-05-11 00:30:00+00:00: scheduled__2025-05-11T00:30:00+00:00, state:running, queued_at: 2025-05-12 08:34:12.384825+00:00. externally triggered: False>
[2025-05-12T08:34:21.637+0000] {logging_mixin.py:190} INFO - Failure caused by unexpected ':'
[2025-05-12T08:34:21.638+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=dags_bash_python_with_xcom, task_id=bash_pull, run_id=scheduled__2025-05-11T00:30:00+00:00, execution_date=20250511T003000, start_date=20250512T083421, end_date=20250512T083421
[2025-05-12T08:34:21.695+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-12T08:34:21.696+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 155 for task bash_pull (unexpected ':'; 206)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3117, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context, jinja_env=jinja_env)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3540, in render_templates
    original_task.render_template_fields(context, jinja_env)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 1442, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/abstractoperator.py", line 775, in _do_render_template_fields
    rendered_content = self.render_template(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 185, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 170, in render_template
    template = jinja_env.from_string(value)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/environment.py", line 1111, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
                               ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/environment.py", line 771, in compile
    self.handle_exception(source=source_hint)
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected ':'
[2025-05-12T08:34:21.740+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-12T08:34:21.773+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-12T08:34:21.778+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
