[2025-05-06T08:52:57.373+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-06T08:52:57.391+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dags_python_with_op_kwargs.regist_t1 scheduled__2025-04-27T17:00:00+00:00 [queued]>
[2025-05-06T08:52:57.398+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dags_python_with_op_kwargs.regist_t1 scheduled__2025-04-27T17:00:00+00:00 [queued]>
[2025-05-06T08:52:57.399+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-05-06T08:52:57.412+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): regist_t1> on 2025-04-27 17:00:00+00:00
[2025-05-06T08:52:57.418+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=739) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-06T08:52:57.419+0000] {standard_task_runner.py:72} INFO - Started process 743 to run task
[2025-05-06T08:52:57.420+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dags_python_with_op_kwargs', 'regist_t1', 'scheduled__2025-04-27T17:00:00+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/dags_python_with_op_kwargs.py', '--cfg-path', '/tmp/tmpdeqademo']
[2025-05-06T08:52:57.421+0000] {standard_task_runner.py:105} INFO - Job 39: Subtask regist_t1
[2025-05-06T08:52:57.660+0000] {task_command.py:467} INFO - Running <TaskInstance: dags_python_with_op_kwargs.regist_t1 scheduled__2025-04-27T17:00:00+00:00 [running]> on host 11348a8299f1
[2025-05-06T08:52:57.720+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dags_python_with_op_kwargs' AIRFLOW_CTX_TASK_ID='regist_t1' AIRFLOW_CTX_EXECUTION_DATE='2025-04-27T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-27T17:00:00+00:00'
[2025-05-06T08:52:57.721+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-05-06T08:52:57.721+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-05-06T08:52:57.721+0000] {logging_mixin.py:190} INFO - Current task name:regist_t1 state:running start_date:2025-05-06 08:52:57.391821+00:00
[2025-05-06T08:52:57.721+0000] {logging_mixin.py:190} INFO - Dag name:dags_python_with_op_kwargs and current dag run status:running
[2025-05-06T08:52:57.721+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-06T08:52:57.722+0000] {logging_mixin.py:190} INFO - 이름: yj
[2025-05-06T08:52:57.722+0000] {logging_mixin.py:190} INFO - 성별: woman
[2025-05-06T08:52:57.722+0000] {logging_mixin.py:190} INFO - 기타: ('hi',)
[2025-05-06T08:52:57.722+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/common/common_func.py", line 13, in regist2
    email = kwargs['email'] or None
            ~~~~~~^^^^^^^^^
KeyError: 'email'
[2025-05-06T08:52:57.729+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-05-06T08:52:57.729+0000] {logging_mixin.py:190} INFO - Task start:2025-05-06 08:52:57.391821+00:00 end:2025-05-06 08:52:57.729401+00:00 duration:0.33758
[2025-05-06T08:52:57.730+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): regist_t1> dag:<DAG: dags_python_with_op_kwargs> dagrun:<DagRun dags_python_with_op_kwargs @ 2025-04-27 17:00:00+00:00: scheduled__2025-04-27T17:00:00+00:00, state:running, queued_at: 2025-05-06 08:52:55.964922+00:00. externally triggered: False>
[2025-05-06T08:52:57.730+0000] {logging_mixin.py:190} INFO - Failure caused by 'email'
[2025-05-06T08:52:57.730+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=dags_python_with_op_kwargs, task_id=regist_t1, run_id=scheduled__2025-04-27T17:00:00+00:00, execution_date=20250427T170000, start_date=20250506T085257, end_date=20250506T085257
[2025-05-06T08:52:57.751+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-06T08:52:57.752+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 39 for task regist_t1 ('email'; 743)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/common/common_func.py", line 13, in regist2
    email = kwargs['email'] or None
            ~~~~~~^^^^^^^^^
KeyError: 'email'
[2025-05-06T08:52:57.797+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-06T08:52:57.957+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-06T08:52:57.964+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
